"""empty message

Revision ID: 00e1f615591e
Revises: dc5a53b1a372
Create Date: 2023-05-08 09:18:20.948851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e1f615591e'
down_revision = 'dc5a53b1a372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.alter_column('activity_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.alter_column('activity_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
