"""empty message

Revision ID: 16a4e676fe15
Revises: 306dcc75a9b3
Create Date: 2023-05-15 12:34:46.580422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a4e676fe15'
down_revision = '306dcc75a9b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_name', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.drop_column('trainer_name')

    # ### end Alembic commands ###
