"""empty message

Revision ID: 28e41c44c4f0
Revises: 8dbe400e42ce
Create Date: 2023-05-03 10:04:06.625570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e41c44c4f0'
down_revision = '8dbe400e42ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainee', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
