"""empty message

Revision ID: 306dcc75a9b3
Revises: db477a29ae67
Create Date: 2023-05-15 11:27:52.860551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306dcc75a9b3'
down_revision = 'db477a29ae67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.drop_column('trainer_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
