"""empty message

Revision ID: 30a6bcd5c588
Revises: 16a4e676fe15
Create Date: 2023-05-17 10:35:52.056038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a6bcd5c588'
down_revision = '16a4e676fe15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.drop_constraint('activity_per_trainer_trainee_id_fkey', type_='foreignkey')
        batch_op.drop_column('trainee_id')
        batch_op.drop_column('trainer_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('trainee_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('activity_per_trainer_trainee_id_fkey', 'trainee', ['trainee_id'], ['id'])

    # ### end Alembic commands ###
