"""empty message

Revision ID: 419e9bac215c
Revises: 
Create Date: 2023-05-17 15:21:39.078837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419e9bac215c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('trainee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'trainee', ['trainee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('trainee_id')
        batch_op.drop_column('trainer_name')

    # ### end Alembic commands ###
