"""empty message

Revision ID: 50a1996b5835
Revises: 136d165147f0
Create Date: 2023-04-24 14:33:38.717000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a1996b5835'
down_revision = '136d165147f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coaching_style_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'coaching_style', ['coaching_style_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('coaching_style_id')

    # ### end Alembic commands ###
