"""empty message

Revision ID: 57e7b82d2500
Revises: 61983411402f
Create Date: 2023-06-07 14:24:44.337501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e7b82d2500'
down_revision = '61983411402f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booked_class')
    op.drop_table('atendencies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atendencies',
    sa.Column('activity_per_trainer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trainee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_per_trainer_id'], ['activity_per_trainer.id'], name='atendencies_activity_per_trainer_id_fkey'),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainee.id'], name='atendencies_trainee_id_fkey'),
    sa.PrimaryKeyConstraint('activity_per_trainer_id', 'trainee_id', name='atendencies_pkey')
    )
    op.create_table('booked_class',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('activity_per_trainer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trainer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trainee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_per_trainer_id'], ['activity_per_trainer.id'], name='booked_class_activity_per_trainer_id_fkey'),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainee.id'], name='booked_class_trainee_id_fkey'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.id'], name='booked_class_trainer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='booked_class_pkey')
    )
    # ### end Alembic commands ###
