"""empty message

Revision ID: 61983411402f
Revises: 2916944befad
Create Date: 2023-05-23 14:56:38.528835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61983411402f'
down_revision = '2916944befad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=10000),
               existing_nullable=True)

    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.alter_column('about',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.alter_column('about',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
