"""empty message

Revision ID: 696f5f2a1bbd
Revises: 28e41c44c4f0
Create Date: 2023-05-04 19:17:50.230526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696f5f2a1bbd'
down_revision = '28e41c44c4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('minutes', sa.String(length=250), nullable=True))
        batch_op.drop_column('slot')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('minutes')
        batch_op.drop_column('hour')

    # ### end Alembic commands ###
