"""empty message

Revision ID: 7a8b0c0b8c0c
Revises: 
Create Date: 2023-05-17 12:42:34.564259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8b0c0b8c0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('location_type', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=250), nullable=True),
    sa.Column('first_name', sa.String(length=250), nullable=True),
    sa.Column('last_name', sa.String(length=250), nullable=True),
    sa.Column('weight', sa.String(length=250), nullable=True),
    sa.Column('height', sa.String(length=250), nullable=True),
    sa.Column('paypal_link', sa.String(length=250), nullable=True),
    sa.Column('gender', sa.String(length=250), nullable=True),
    sa.Column('user_role', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body_type', sa.String(length=250), nullable=True),
    sa.Column('goal', sa.String(length=250), nullable=True),
    sa.Column('fitness_experience', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('about', sa.String(length=250), nullable=True),
    sa.Column('experience_level', sa.String(length=250), nullable=True),
    sa.Column('bank_account', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=250), nullable=True),
    sa.Column('specialty', sa.String(length=250), nullable=True),
    sa.Column('coaching_style', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_per_trainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('duration', sa.String(length=250), nullable=True),
    sa.Column('location_range', sa.String(length=250), nullable=True),
    sa.Column('location_pinpoint', sa.String(length=250), nullable=True),
    sa.Column('price', sa.String(length=250), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('hour', sa.String(length=250), nullable=True),
    sa.Column('minutes', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=250), nullable=True),
    sa.Column('lat', sa.String(length=250), nullable=True),
    sa.Column('lng', sa.String(length=250), nullable=True),
    sa.Column('trainer_name', sa.String(length=250), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('trainee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainee.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atendencies',
    sa.Column('activity_per_trainer_id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_per_trainer_id'], ['activity_per_trainer.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainee.id'], ),
    sa.PrimaryKeyConstraint('activity_per_trainer_id', 'trainee_id')
    )
    op.create_table('booked_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=250), nullable=True),
    sa.Column('activity_per_trainer_id', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('trainee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_per_trainer_id'], ['activity_per_trainer.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainee.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booked_class')
    op.drop_table('atendencies')
    op.drop_table('activity_per_trainer')
    op.drop_table('trainer')
    op.drop_table('trainee')
    op.drop_table('user')
    op.drop_table('activity')
    # ### end Alembic commands ###
