"""empty message

Revision ID: 8c736829d946
Revises: 10a6e8471cac
Create Date: 2023-05-05 21:04:58.357437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c736829d946'
down_revision = '10a6e8471cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('activity_per_trainer_activity_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'activity', ['activity_id'], ['id'])
        batch_op.drop_column('activity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('activity_per_trainer_activity_fkey', 'activity', ['activity'], ['id'])
        batch_op.drop_column('activity_id')

    # ### end Alembic commands ###
