"""empty message

Revision ID: a4424259c303
Revises: e82946733ecf
Create Date: 2023-04-26 17:15:33.712923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4424259c303'
down_revision = 'e82946733ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gender_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
