"""empty message

Revision ID: a6fe2eef9a40
Revises: 7a8b0c0b8c0c
Create Date: 2023-05-17 13:33:50.576829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fe2eef9a40'
down_revision = '7a8b0c0b8c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainee_name', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.drop_column('trainee_name')

    # ### end Alembic commands ###
