"""empty message

Revision ID: d67d417f9385
Revises: a4424259c303
Create Date: 2023-04-27 20:14:36.966415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67d417f9385'
down_revision = 'a4424259c303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
