"""empty message

Revision ID: dc5a53b1a372
Revises: 12d61d7c1a63
Create Date: 2023-05-08 09:15:41.287407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5a53b1a372'
down_revision = '12d61d7c1a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.alter_column('activity_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.alter_column('activity_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
