"""empty message

Revision ID: ee86c207bab3
Revises: 9be923f9e787
Create Date: 2023-05-23 02:34:24.386474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee86c207bab3'
down_revision = '9be923f9e787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_profile_image_url', sa.String(length=250), nullable=True))

    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=250), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_url', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.drop_column('profile_image_url')

    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.drop_column('trainer_profile_image_url')

    # ### end Alembic commands ###
