"""empty message

Revision ID: f5cc97919e31
Revises: 6de4ba3fec30
Create Date: 2023-05-10 16:23:28.225219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5cc97919e31'
down_revision = '6de4ba3fec30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_per_trainer', schema=None) as batch_op:
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
